#pragma config(Motor,  port2,           LMotor,        tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port3,           RMotor,        tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port4,           LElevator,     tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port5,           RElevator,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port6,           LDoor,         tmotorServoStandard, openLoop)
#pragma config(Motor,  port7,           RDoor,         tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*===================================================================================*/
task GottaGoFast()
{
	float left, right;	//Variables for calculating
	while (true)
	{
		if(abs(vexRT[Ch3]) < 10 && abs(vexRT[Ch2]) < 10)	//To account for any human flinching
		{
			motor[LMotor] = 0;
			motor[RMotor] = 0;
		}
		else
		{
			left = pow(vexRT[Ch3], 3)/pow(127, 2);	//Slope calculation for smooth speed increase
			right = pow(vexRT[Ch2], 3)/pow(127, 2);

			if(left > 127)
			{
				left = 127;
			}
			else if(left < -127)
			{
				left = -127;
			}
			if(right > 127)
			{
				right = 127;
			}
			else if(right < -127)
			{
				right = -127;
			}
			motor[LMotor] = left;	//Send the values to the motors
			motor[RMotor] = right;
		}
	}
}

/*===================================================================================*/

task UpperAndDowners()
{
	while(true)
	{
		if(vexRT[Btn6U] == true)
		{
			motor[LElevator] = -75;
			motor[RElevator] = -127;
		}
		else if(vexRT[Btn6D] == true)
		{
			motor[LElevator] = 75;
			motor[RElevator] = 127;
		}
		else
		{
			motor[LElevator] = 0;
			motor[RElevator] = 0;
		}
	}
}

/*===================================================================================*/

task SlidinIntoDMs ()
{
	motor[LDoor] = 300;
	motor[RDoor] = 300;
	while(true)
	{
		if(vexRT[Btn8R] == true)	//Close
		{
			motor[LDoor] = 300;
			motor[RDoor] = 300;
		}
		else if(vexRT[Btn8L] == true)	//Open
		{
			motor[LDoor] = -23;
			motor[RDoor] = -25;
		}
	}
}

task Autonomous()
{
	motor[LMotor] = 90;
	motor[RMotor] = 127;
	wait1Msec(1500);
	motor[LMotor] = 127;
	motor[RMotor] = -127;
	wait1Msec(500);
	motor[LMotor] = 127;
	motor[RMotor] = 127;
	wait1Msec(2000);
	motor[LMotor] = 0;
	motor[RMotor] = 0;
}

task main()
{
	startTask(GottaGoFast);
	startTask(UpperAndDowners);
	startTask(SlidinIntoDMs);

	bool Auto = false;

	while(true)
	{
		if(vexRT[Btn8U] == true && Auto == false)
		{
			stopTask(GottaGoFast);
			startTask(Autonomous);
			Auto = true;
		}
		else if(Auto == true && (abs(vexRT[Ch3]) > 10 || abs(vexRT[Ch2]) > 10 || abs(vexRT[Ch1]) > 0 || abs(vexRT[Ch4]) > 10))
		{
			stopTask(Autonomous);
			startTask(GottaGoFast);
			Auto = false;
		}
	}
}
