#pragma config(Motor,  port2,           LMotor,        tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port3,           RMotor,        tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port4,           LwnMotor,      tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port5,           PowPow,        tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port6,           OptPrime,      tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

	bool autoA;
	bool autoB;

task GottaGoFast()
{
float left, right;
while (true)
	{
		if(abs(vexRT[Ch3]) < 10 && abs(vexRT[Ch2]) < 10)
		{
			motor[LMotor] = 0;
			motor[RMotor] = 0;
		}
		else
		{
			left = pow(vexRT[Ch3], 3)/pow(127, 2);
			right = pow(vexRT[Ch2], 3)/pow(127, 2);

			if(left > 127)
			{
				left = 127;
			}
			else if(left < -127)
			{
				left = -127;
			}
			if(right > 127)
			{
			 right = 127;
			}
			else if(right < -127)
			{
				right = -127;
			}
			motor[LMotor] = left;
			motor[RMotor] = right;
		} // Watch for wheels
	}
}

task GrassEater()
{
	while (true)
	{
		if (vexRT[Btn6U] == true)
		{
			motor[LwnMotor] = 90;
		}
		else if (vexRT[Btn6D] == true)
		{
			motor[LwnMotor] = -90;
		}
		else
		{
			motor[LwnMotor] = 0;
		}
	}
}

task BlamBlam()
{
	while (true)
	{
		if (vexRT[Btn8R] == true)
		{
			motor[PowPow] = -90;
		}
		else
		{
			motor[PowPow] = 0;
		}
	}
}

task AutoBots()
{
motor[LMotor] = 127;
motor[RMotor] = 127;
wait1Msec(3300);
motor[LMotor] = 0;
motor[RMotor] = 0;
wait1Msec(15);
motor[OptPrime] = 70;
wait1Msec(50);
motor[LMotor] = -127;
motor[RMotor] = -127;
wait1Msec(150);
motor[OptPrime] = 0;
startTask(GottaGoFast);
}

task RollOut()
{
motor[LMotor] = 127;
motor[RMotor] = 127;
wait1Msec(700);
motor[LMotor] = 0;
motor[RMotor] = 0;
wait1Msec(15);
motor[OptPrime] = 70;
wait1Msec(50);
motor[LMotor] = -127;
motor[RMotor] = -127;
wait1Msec(150);
motor[OptPrime] = 0;
startTask(GottaGoFast);
}

task main()
{
	startTask(GottaGoFast);
	startTask(GrassEater);
	startTask(BlamBlam);

	autoA = false;
	autoB = false;

	while(true)
	{
		wait1Msec(10);

		if (vexRT[Btn7U] == true && autoA == false)
		{
			autoA = true;
			startTask(AutoBots);
			stopTask(GottaGoFast);
		}
		else if (autoA == true && (abs(vexRT[Ch2]) > 10 || abs(vexRT[Ch3]) > 10))
		{
			autoA = false;
			stopTask(AutoBots);
			startTask(GottaGoFast);
		}
		if (vexRT[Btn7R] == true && autoB == false)
		{
			autoB = true;
			startTask(RollOut);
			stopTask(GottaGoFast);
		}
		else if (autoB == true && (abs(vexRT[Ch2]) > 10 || abs(vexRT[Ch3]) > 10))
		{
			autoB = false;
			stopTask(RollOut);
			startTask(GottaGoFast);
		}
	}
}
