#pragma config(Sensor, in1,    Pot,            sensorPotentiometer)
#pragma config(Motor,  port3,           mannyServo,    tmotorServoStandard, openLoop)
#pragma config(Motor,  port4,           LMotor,        tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port5,           deflectorServo, tmotorServoStandard, openLoop)
#pragma config(Motor,  port6,           Wall,          tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port7,           Shooter,       tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port8,           RMotor,        tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port9,           Shooter,       tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//bool driveSpeed = false; //Boolean variable for drive speed
//float wallPos = 0; //Float variable for the wall position

task Chasis()
{
	float left, right;	//Variables for calculating
	while (true)
	{
		if(abs(vexRT[Ch3]) < 10 && abs(vexRT[Ch2]) < 10)	//To account for any human flinching
		{
			motor[LMotor] = 0;
			motor[RMotor] = 0;
		}
		else
		{
			left = (vexRT[Ch3] * abs(vexRT[Ch3])) / 127;	//Slope calculation for smooth speed increase
			right = (vexRT[Ch2] * abs(vexRT[Ch2])) / 127;

			if(left > 127)	//Crutches to ensure we don't overpower the motors
			{
				left = 127;
			}
			else if(left < -127)
			{
				left = -127;
			}
			if(right > 127)
			{
				right = 127;
			}
			else if(right < -127)
			{
				right = -127;
			}
			motor[LMotor] = left;	//Send the values to the motors
			motor[RMotor] = right;
		}
	}
}

//Task for running the Wall
task wallDrive()
{
	while(true)
	{
		if(vexRT[Ch2] < 10 && vexRT[Ch2] > -10)
		{
			motor[Wall] = 0;
		}
		else
		{
			motor[Wall] = -vexRT[Ch2];
		}
	}
}

//Task for running the shooter
task Shoot()
{
	while(true)
	{
		while(vexRT[Btn6U] == true)//While the top right button on the back of the controller is pressed down, the shooter runs in 1/3 second increments, always ending at the same position
		{
			motor[Shooter] = 127;
		}
		//wait1Msec(339);
		motor[Shooter] = 0;
	}
}

int hotLow = -30;
int hotMid = -127;
int deflectorAngle;

//Task for the shooter's deflector angle
task Deflector()
{
	deflectorAngle = hotMid;
	motor[deflectorServo] = deflectorAngle;
	while(true)
	{
		if(vexRT[Btn8L] == true)
		{
			deflectorAngle = hotLow;
		}
		if(vexRT[Btn8U] == true)
		{
			deflectorAngle = hotMid;
		}
		motor[deflectorServo] = deflectorAngle;
	}
}

//Task for the Manny Getter servo
task mannyGetter()
{
	while(true)
	{
		if(vexRT[Btn8D] == true)
		{
			motor[mannyServo] = -127;
		}
		else if(vexRT[Btn8R] == true)
		{
			motor[mannyServo] = 7;
		}
	}
}

task main()
{
	motor[mannyServo] = 7;
	startTask(Chasis);
	startTask(wallDrive);
	startTask(Deflector);
	startTask(Shoot);
	startTask(mannyGetter);
	while(true)
	{
		wait1Msec(1);
	}
}
