#pragma config(Motor,  port2,           rightMotor,    tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port3,           leftMotor,     tmotorNormal, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

float x = vexRT[Ch4];
float y = vexRT[Ch3];

task main ()
{
  while(1 == 1)
  {
    motor[leftMotor]  = (y + x)/2;
    motor[rightMotor] = (y - x)/2;
  }
}
