#pragma config(Sensor, in1,    Pot,            sensorPotentiometer)
#pragma config(Motor,  port2,           rightWheelMotor, tmotorVex393_MC29, openLoop, driveRight)
#pragma config(Motor,  port4,           Wall,          tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port7,           leftWheelMotor, tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port9,           Shooter,       tmotorVex269_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

bool driveSpeed = false; //Boolean variable for drive speed
//float wallPos = 0; //Float variable for the wall position

task arcadeDrive()
{
	while(true)
	{

		if(driveSpeed == false)
		{
			if(abs(vexRT[Ch3]) < 10 && abs(vexRT[Ch4]) < 10) //Dead zone when joystick at approximately zero
			{
				motor[leftWheelMotor]  = 0;
				motor[rightWheelMotor] = 0;
			}
			else //Arcade drive on left joystick and full speed with 127 barrier
			{
				float y = vexRT[Ch4];
				float x = vexRT[Ch3];
				float xPlusY = x + y;
				float xMinusY = x - y;
				if(xPlusY > 127)
				{
					xPlusY = 127;
				}
				else if(xPlusY < -127)
				{
					xPlusY = -127;
				}
				if(xMinusY > 127)
				{
					xMinusY = 127;
				}
				else if(xMinusY < -127)
				{
					xMinusY = -127;
				}
				motor[leftWheelMotor]  = xPlusY;
				motor[rightWheelMotor] = xMinusY;
			}
		}
		else if(driveSpeed == true)//Optional half-speed
		{
			motor[leftWheelMotor]  = (vexRT[Ch3] + vexRT[Ch4])/2;
			motor[rightWheelMotor] = (vexRT[Ch3] - vexRT[Ch4])/2;
		}
		if(vexRT[Btn5D] == true)
		{
			driveSpeed = true;
		}
		if(vexRT[Btn5U] == true)
		{
			driveSpeed = false;
		}
	}
}

task WallandShooterAngle()
{
	while(true)
	{
		if(vexRT[Ch2] < 10 && vexRT[Ch2] > -10)
		{
			motor[Wall] = 0;
		}
		else
		{
			motor[Wall] = vexRT[Ch2];
		}
	}
}

task Shoot()
{
	while(true)
	{
		while(vexRT[Btn6U] == true)//While the top right button on the back of the controller is pressed down, the shooter runs
		{
			motor[Shooter] = 127;
		}
		motor[Shooter] = 0;
	}
}

task main()
{
	startTask(arcadeDrive);
	startTask(WallandShooterAngle);
	startTask(Shoot);
	while(true)
	{
		wait1Msec(1);
	}
}
