#pragma config(Sensor, in1,    Pot,            sensorPotentiometer)
#pragma config(Motor,  port2,            ,             tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           mannyServo,    tmotorServoStandard, openLoop)
#pragma config(Motor,  port4,           LMotor,        tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port5,           deflectorShooter, tmotorNone, openLoop)
#pragma config(Motor,  port6,           Wall,          tmotorNone, openLoop)
#pragma config(Motor,  port7,           Shooter,       tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port8,           RMotor,        tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port9,           Shooter,       tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//bool driveSpeed = false; //Boolean variable for drive speed
//float wallPos = 0; //Float variable for the wall position

task Chasis()
{
	float left, right;	//Variables for calculating
	while (true)
	{
		if(abs(vexRT[Ch3]) < 10 && abs(vexRT[Ch2]) < 10)	//To account for any human flinching
		{
			motor[LMotor] = 0;
			motor[RMotor] = 0;
		}
		else
		{
			left = (vexRT[Ch3] * abs(vexRT[Ch3])) / 127;	//Slope calculation for smooth speed increase
			right = (vexRT[Ch2] * abs(vexRT[Ch2])) / 127;

			if(left > 127)	//Crutches to ensure we don't overpower the motors
			{
				left = 127;
			}
			else if(left < -127)
			{
				left = -127;
			}
			if(right > 127)
			{
				right = 127;
			}
			else if(right < -127)
			{
				right = -127;
			}
			motor[LMotor] = left;	//Send the values to the motors
			motor[RMotor] = right;
		}
	}
}

task main()
{
	startTask(Chasis);
	startTask(wallDrive);
	startTask(Shoot);
	while(true)
	{
		wait1Msec(10);
	}
}
